# Generated by Django 4.2.17 on 2025-01-03 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0002_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
